[project]
name = "frostspin"
requires-python = ">=3.10"
dependencies = [
  "numpy >= 2.0",
  "scipy >= 1.12",
  "sympy >= 1.11",
  "numba >= 0.62",
]
authors = [
  {name = "Olivier Gauthé", email = "olivier.gauthe@quobly.io"},
]
description = "A Symmetric Tensor library for lattice spin systems at finite temperature."
keywords = ["Quantum physics", "Tensor Networks", "Symmetries"]
classifiers = [
  "Intended Audience :: Science/Research",
  "Operating System :: MacOS",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Quantum Computing",
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/ogauthe/frostspin"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "frostspin/config.py"

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
  'A',
  'ARG',
  'B',
  'C',
  'E',
  'EXE',
  'F',
  'FBT',
  'FLY',
  'FURB',
  'I',
  'ICN',
  'INP',
  'ISC',
  'N',
  'NPY',
  'PERF',
  'PGH',
  'PIE',
  'PL',
  'Q',
  'RET',
  'RSE',
  'RUF',
  'SIM',
  'SLF',
  'TID',
  'TRY',
  'UP',
  'W'
]
ignore = [
    "C901",  # too demanding
    "N802",  # prefer keeping toU1
    "N803",  # prefer keeping D
    "N806",  # prefer keeping D
    "N816",  # prefer keeping hU1
    "TRY003",  # simpler with explicit message
    "RUF012",  # not using type annotation
    "PLR0912", # too pedantic
    "PLR0913", # too pedantic
    "PLR0915", # too pedantic
    "PLR2004", # too pedantic
]
